dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  timeago: ^3.3.0
  video_player: ^2.4.7
  cached_network_image: ^3.2.3
  provider: ^6.0.5
  http: ^0.13.5
  shared_preferences: ^2.0.17